"""add exclude_from_reports to categories

Revision ID: 00cf032c8fec
Revises: 0b708f9a99bd
Create Date: 2026-08-05 16:25:36.033089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cf032c8fec'
down_revision: Union[str, Sequence[str], None] = '0b708f9a99bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('exclude_from_reports', sa.Boolean(), nullable=False, server_default=sa.false()))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'exclude_from_reports')
    # ### end Alembic commands ###
