"""baseline: existing accounts categories transactions tables

Revision ID: 0b708f9a99bd
Revises: 3bfdd2657c45
Create Date: 2026-08-05 15:54:37.119627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b708f9a99bd'
down_revision: Union[str, Sequence[str], None] = '3bfdd2657c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
