"""create transactions table

Revision ID: 6583cb46dde3
Revises: 00cf032c8fec
Create Date: 2026-08-07 18:03:36.906065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6583cb46dde3'
down_revision: Union[str, Sequence[str], None] = '00cf032c8fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_raw_import_hash'), table_name='transactions')
    op.create_index(op.f('ix_transactions_raw_import_hash'), 'transactions', ['raw_import_hash'], unique=False)
    op.create_unique_constraint('uq_transaction_user_hash', 'transactions', ['user_id', 'raw_import_hash'])
    op.drop_constraint(op.f('transactions_account_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_category_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key('fk_transactions_account_id', 'transactions', 'accounts', ['account_id'], ['id'],
                          ondelete='CASCADE')
    op.create_foreign_key('fk_transactions_category_id', 'transactions', 'categories', ['category_id'], ['id'],
                          ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_account_id', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_category_id', 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_category_id_fkey'), 'transactions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('transactions_account_id_fkey'), 'transactions', 'accounts', ['account_id'], ['id'])
    op.drop_constraint('uq_transaction_user_hash', 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_raw_import_hash'), table_name='transactions')
    op.create_index(op.f('ix_transactions_raw_import_hash'), 'transactions', ['raw_import_hash'], unique=True)
    # ### end Alembic commands ###
